### ISSUE TITLE
wrong message when try to open new shop and fails

### ISSUE THREAD

**Issue by inbarbc** [inbarbc/StockMarket_Project#553]
if the user is not filling one of the fields in "open new shop" -> exit "open new shop" window and write a success indicate message. should be fail message.

it happens also when one or more of the fields in empty, and also when the shop name in not unique. 

![Image](https://github.com/inbarbc/StockMarket_Project/assets/102466931/dfc67f9c-d45a-475b-8ffd-8db17354b9dc)

![Image](https://github.com/inbarbc/StockMarket_Project/assets/102466931/0b1a8af5-4581-4f04-8e7e-174427596755)

**Comment by saadao** [comment]
fixed 



![Image](https://github.com/inbarbc/StockMarket_Project/assets/104302884/b2946749-835c-4823-a153-96203d556036)



shops are reloaded after trying to add new shop 
error message was missing
